# audio_generation.py
import os
import logging
import tempfile
from pathlib import Path
from typing import Optional, List
from gtts import gTTS
import re
import html

# Optional: use pydub if available
try:
    from pydub import AudioSegment
    PydubAvailable = True
except Exception:
    PydubAvailable = False

# ---------------- LOGGING ----------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler("audio_generation.log", encoding="utf-8"),
        logging.StreamHandler()
    ],
)

# ---------------- CLEANING HELPER ----------------
def clean_for_audio(text: str) -> str:
    """
    Cleans text for natural speech:
    Removes markdown, code blocks, bullets, and redundant punctuation.
    """
    if not text:
        return ""

    text = html.unescape(text)  # Decode HTML entities like &amp;
    text = re.sub(r"\[.*?\]", "", text)  # Remove [bracketed text]
    text = re.sub(r"[#*_>`~^=+\[\]\(\)\{\}\|\\/]", " ", text)  # Remove markdown symbols
    text = re.sub(r"(\*\*|__)(.*?)\1", r"\2", text)  # Remove bold/italic markers
    text = re.sub(r"[\u2022•◦▪\-•]+", " ", text)  # Remove bullets
    text = re.sub(r"\b\d+[\.\)]\s*", "", text)  # Remove numbered list prefixes
    text = re.sub(r"\s+", " ", text).strip()  # Clean extra spaces
    text = re.sub(r"\s+([,.!?;:])", r"\1", text)  # Fix space before punctuation
    return text.strip()

# ---------------- gTTS CHUNK SYNTH ----------------
def _gtts_chunk_and_save(text: str, target_dir: Path, prefix: str = "part", max_chars: int = 4500) -> List[Path]:
    """
    Safely chunk text for gTTS (limit ~5000 chars), synthesize each chunk to MP3.
    Returns list of MP3 part paths.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    text = clean_for_audio(text)  # ✅ extra safeguard cleaning here too

    # Split by sentences
    sentences = re.split(r'(?<=[.!?])\s+', text)
    parts = []
    current = ""
    for s in sentences:
        if len(current) + len(s) + 1 <= max_chars:
            current += (s + " ")
        else:
            if current.strip():
                parts.append(current.strip())
            current = s + " "
    if current.strip():
        parts.append(current.strip())

    out_files = []
    for i, p in enumerate(parts):
        out_path = target_dir / f"{prefix}_{i:03d}.mp3"
        try:
            gTTS(text=clean_for_audio(p), lang="en").save(str(out_path))
            out_files.append(out_path)
        except Exception as e:
            logging.error(f"gTTS failed for chunk {i}: {e}")
            if PydubAvailable:
                silent = AudioSegment.silent(duration=300)
                silent.export(str(out_path), format="mp3")
                out_files.append(out_path)
            else:
                out_path.write_bytes(b"")
                out_files.append(out_path)
    return out_files

# ---------------- MAIN SYNTHESIS ----------------
def synthesize_audio(text: str, out_path: str) -> Optional[str]:
    """
    Convert full text to a single MP3 file.
    Cleans and chunks text automatically.
    """
    if not text or not text.strip():
        logging.warning("⚠️ Empty text passed to synthesize_audio()")
        return None

    text = clean_for_audio(text)
    out_path = Path(out_path)
    temp_dir = Path(tempfile.mkdtemp(prefix="tts_parts_"))

    try:
        parts = _gtts_chunk_and_save(text, temp_dir)
        if not parts:
            logging.error("❌ No parts generated by gTTS.")
            return None

        if PydubAvailable:
            combined = None
            for p in parts:
                try:
                    seg = AudioSegment.from_file(p)
                except Exception as e:
                    logging.warning(f"pydub failed to read {p}: {e}")
                    continue
                if combined is None:
                    combined = seg
                else:
                    combined += AudioSegment.silent(duration=300) + seg

            if combined is None:
                logging.error("pydub could not read any generated parts.")
                parts[0].replace(out_path)
                return str(out_path)

            out_path.parent.mkdir(parents=True, exist_ok=True)
            combined.export(str(out_path), format="mp3", bitrate="192k")
            logging.info(f"✅ Audiobook generated: {out_path}")
            return str(out_path)
        else:
            # fallback: just return first file
            first = parts[0]
            out_path.parent.mkdir(parents=True, exist_ok=True)
            first.replace(out_path)
            logging.warning("pydub not installed: returning first part only.")
            return str(out_path)
    except Exception as e:
        logging.exception("synthesize_audio failed")
        return None
    finally:
        try:
            for p in list(temp_dir.glob("*")):
                p.unlink()
            temp_dir.rmdir()
        except Exception:
            pass

# ---------------- TEST MODE ----------------
if __name__ == "__main__":
    Path("outputs").mkdir(exist_ok=True)
    sample = """
    ## Heart Disease Prediction
    **Abstract:** Heart disease prediction uses AI and ML techniques.
    It analyzes patient data for early diagnosis and better treatment.
    """
    out = synthesize_audio(sample, "outputs/demo_cleaned_audio.mp3")
    print("Generated:", out)
